function requireState(definition, stateName) {
  const state = definition?.[stateName];
  if (!state || !Array.isArray(state.positionKm) || !Array.isArray(state.velocityKmPerS)
    || state.positionKm.length !== 3 || state.velocityKmPerS.length !== 3) {
    throw new Error(`Scenario definition is missing ${stateName} Cartesian state (km, km/s).`);
  }
  return state;
}

function getFormalScenarioState(scenario, role) {
  const spacecraft = scenario.definition?.spacecraft?.[role];
  const state = spacecraft?.initialState;
  if (!state || !Array.isArray(state.position) || !Array.isArray(state.velocity)) {
    return null;
  }
  return {
    epochUtc: scenario.definition.epoch,
    positionKm: state.position,
    velocityKmPerS: state.velocity,
  };
}

function generateGmatScript({ scenario, finalDecisionVariables, reportPath }) {
  const definition = scenario.definition;
  const chaser = getFormalScenarioState(scenario, "chaser") ?? requireState(definition, "chaserInitialState");
  const target = getFormalScenarioState(scenario, "target") ?? requireState(definition, "targetInitialState");
  const epoch = chaser.epochUtc;
  if (!epoch || epoch !== target.epochUtc) {
    throw new Error("Chaser and target must use the same epochUtc for local GMAT validation.");
  }
  const frame = definition.coordinateSystem ?? definition.referenceFrame ?? "EarthMJ2000Eq";
  const gravity = definition.forceModel?.gravity;
  const lines = [
    "% Generated by Mission Dashboard. Units: km, km/s, s.",
    "Create Spacecraft Chaser;", "Create Spacecraft Target;",
    `GMAT Chaser.DateFormat = UTCGregorian;`, `GMAT Target.DateFormat = UTCGregorian;`,
    `GMAT Chaser.Epoch = '${epoch}';`, `GMAT Target.Epoch = '${epoch}';`,
    `GMAT Chaser.CoordinateSystem = ${frame};`, `GMAT Target.CoordinateSystem = ${frame};`,
    "GMAT Chaser.DisplayStateType = Cartesian;", "GMAT Target.DisplayStateType = Cartesian;",
    ...["X", "Y", "Z", "VX", "VY", "VZ"].flatMap((key, index) => [
      `GMAT Chaser.${key} = ${[...chaser.positionKm, ...chaser.velocityKmPerS][index]};`,
      `GMAT Target.${key} = ${[...target.positionKm, ...target.velocityKmPerS][index]};`,
    ]),
    "Create ForceModel FM;", "GMAT FM.CentralBody = Earth;", "GMAT FM.PrimaryBodies = {Earth};",
    ...(gravity ? [
      `GMAT FM.GravityField.Earth.Degree = ${gravity.degree};`,
      `GMAT FM.GravityField.Earth.Order = ${gravity.order};`,
    ] : []),
    "Create Propagator Prop;", "GMAT Prop.FM = FM;", "GMAT Prop.Type = PrinceDormand78;",
    "Create ReportFile ValidationReport;", `GMAT ValidationReport.Filename = '${reportPath.replaceAll("\\", "/")}';`,
    "GMAT ValidationReport.Add = {Chaser.X, Chaser.Y, Chaser.Z, Target.X, Target.Y, Target.Z};", "BeginMissionSequence;",
  ];
  if (finalDecisionVariables.tWait > 0) lines.push(`Propagate Prop(Chaser, Target) {Chaser.ElapsedSecs = ${finalDecisionVariables.tWait}};`);
  finalDecisionVariables.burns.forEach((burn, index) => {
    const name = `Burn${index + 1}`;
    lines.push(`Create ImpulsiveBurn ${name};`, `GMAT ${name}.Element1 = ${burn.deltaV[0]};`, `GMAT ${name}.Element2 = ${burn.deltaV[1]};`, `GMAT ${name}.Element3 = ${burn.deltaV[2]};`, `Maneuver ${name}(Chaser);`);
    if (burn.timeToNextBurn != null) lines.push(`Propagate Prop(Chaser, Target) {Chaser.ElapsedSecs = ${burn.timeToNextBurn}};`);
  });
  lines.push(`Propagate Prop(Chaser, Target) {Chaser.ElapsedSecs = ${finalDecisionVariables.finalCoastTime}};`, "Report ValidationReport Chaser.X Chaser.Y Chaser.Z Target.X Target.Y Target.Z;");
  return `${lines.join("\n")}\n`;
}

module.exports = { generateGmatScript };
