function requireState(definition, stateName) {
  const state = definition?.[stateName];
  if (!state || !Array.isArray(state.positionKm) || !Array.isArray(state.velocityKmPerS)
    || state.positionKm.length !== 3 || state.velocityKmPerS.length !== 3) {
    throw new Error(`Scenario definition is missing ${stateName} Cartesian state (km, km/s).`);
  }
  return state;
}

function getFormalScenarioState(scenario, role) {
  const definition = scenario.scenarioJson ?? scenario.definition;
  const spacecraft = definition?.spacecraft?.[role];
  const position = spacecraft?.positionKm ?? spacecraft?.initialState?.position;
  const velocity = spacecraft?.velocityKmPerSec ?? spacecraft?.initialState?.velocity;
  if (!Array.isArray(position) || !Array.isArray(velocity)) {
    return null;
  }
  return {
    epochUtc: definition.epoch?.value ?? definition.epoch,
    positionKm: position,
    velocityKmPerS: velocity,
  };
}

function generateGmatScript({ scenario, finalDecisionVariables, reportPath }) {
  const definition = scenario.scenarioJson ?? scenario.definition;
  const chaser = getFormalScenarioState(scenario, "chaser") ?? requireState(definition, "chaserInitialState");
  const target = getFormalScenarioState(scenario, "target") ?? requireState(definition, "targetInitialState");
  const epoch = chaser.epochUtc;
  if (!epoch || epoch !== target.epochUtc) {
    throw new Error("Chaser and target must use the same epochUtc for local GMAT validation.");
  }
  const frame = definition.coordinateSystem ?? definition.referenceFrame ?? "EarthMJ2000Eq";
  const gravity = definition.forceModel?.gravityField ?? definition.forceModel?.gravity;
  const propagator = definition.propagator ?? {};
  const chaserName = "ChaserSC";
  const targetName = "TargetSC";
  const burnDefinitions = finalDecisionVariables.burns.flatMap((burn, index) => {
    const name = `Burn${index + 1}`;
    return [
      `Create ImpulsiveBurn ${name};`,
      `GMAT ${name}.Element1 = ${burn.deltaV[0]};`,
      `GMAT ${name}.Element2 = ${burn.deltaV[1]};`,
      `GMAT ${name}.Element3 = ${burn.deltaV[2]};`,
      `GMAT ${name}.CoordinateSystem = ${frame};`,
      `GMAT ${name}.DecrementMass = false;`,
    ];
  });
  const lines = [
    "% Generated by Mission Dashboard. Units: km, km/s, s.",
    `Create Spacecraft ${chaserName};`, `Create Spacecraft ${targetName};`,
    `GMAT ${chaserName}.DateFormat = UTCGregorian;`, `GMAT ${targetName}.DateFormat = UTCGregorian;`,
    `GMAT ${chaserName}.Epoch = '${epoch}';`, `GMAT ${targetName}.Epoch = '${epoch}';`,
    `GMAT ${chaserName}.CoordinateSystem = ${frame};`, `GMAT ${targetName}.CoordinateSystem = ${frame};`,
    `GMAT ${chaserName}.DisplayStateType = Cartesian;`, `GMAT ${targetName}.DisplayStateType = Cartesian;`,
    ...["X", "Y", "Z", "VX", "VY", "VZ"].flatMap((key, index) => [
      `GMAT ${chaserName}.${key} = ${[...chaser.positionKm, ...chaser.velocityKmPerS][index]};`,
      `GMAT ${targetName}.${key} = ${[...target.positionKm, ...target.velocityKmPerS][index]};`,
    ]),
    "Create ForceModel FM;", "GMAT FM.CentralBody = Earth;", "GMAT FM.PrimaryBodies = {Earth};",
    ...(gravity ? [
      `GMAT FM.GravityField.Earth.Degree = ${gravity.degree};`,
      `GMAT FM.GravityField.Earth.Order = ${gravity.order};`,
    ] : []),
    "Create Propagator Prop;", "GMAT Prop.FM = FM;",
    `GMAT Prop.Type = ${propagator.integrator ?? "RungeKutta89"};`,
    `GMAT Prop.InitialStepSize = ${propagator.initialStepSec ?? 60};`,
    `GMAT Prop.MaxStep = ${propagator.maxStepSec ?? 1};`,
    `GMAT Prop.MinStep = ${propagator.minStepSec ?? 0.001};`,
    `GMAT Prop.Accuracy = ${propagator.accuracy ?? 1e-12};`,
    "Create ReportFile ValidationReport;", `GMAT ValidationReport.Filename = '${reportPath.replaceAll("\\", "/")}';`,
    `GMAT ValidationReport.Add = {${chaserName}.X, ${chaserName}.Y, ${chaserName}.Z, ${targetName}.X, ${targetName}.Y, ${targetName}.Z};`,
    ...burnDefinitions,
    "BeginMissionSequence;",
  ];
  if (finalDecisionVariables.tWait > 0) lines.push(`Propagate Prop(${chaserName}, ${targetName}) {${chaserName}.ElapsedSecs = ${finalDecisionVariables.tWait}};`);
  finalDecisionVariables.burns.forEach((burn, index) => {
    const name = `Burn${index + 1}`;
    lines.push(`Maneuver ${name}(${chaserName});`);
    if (burn.timeToNextBurn != null) lines.push(`Propagate Prop(${chaserName}, ${targetName}) {${chaserName}.ElapsedSecs = ${burn.timeToNextBurn}};`);
  });
  lines.push(
    `Propagate Prop(${chaserName}, ${targetName}) {${chaserName}.ElapsedSecs = ${finalDecisionVariables.finalCoastTime}};`,
    `Report ValidationReport ${chaserName}.X ${chaserName}.Y ${chaserName}.Z ${targetName}.X ${targetName}.Y ${targetName}.Z;`,
  );
  return `${lines.join("\n")}\n`;
}

module.exports = { generateGmatScript };
